### PR TITLE
Feature/main ecbuild candidate 20220111

### LINKED ISSUE #27: Merge with GFDL
## Description
There are a few changes (mainly making private data structure public) that would need to be merged back into GFDL's code.

### PR DESCRIPTION
**Pull request by guillaumevernieres**
## Description
closes #27

### CODE REVIEW

**Comment by HamidehGMAO** [comment]
my build on discover with intel fails with this error

image

**Comment by guillaumevernieres** [comment]
@HamidehGMAO , you need to edit the soca/bundle/CMakeLists.txt and replance the mom6 branch with this one.

**Comment by HamidehGMAO** [comment]
> @HamidehGMAO , you need to edit the soca/bundle/CMakeLists.txt and replance the mom6 branch with this one.

@guillaumevernieres just did it, but got the same error

**Comment by liuxiao37k** [comment]
I was able to successfully build soca bundle on both Orion and Hera (Intel compilers) with BGC option `=ON`. 
On Hera, all soca ctest passed except `test_soca_convertstate`, `test_soca_dirac_soca_mask`, `test_soca_3dvarbump`. But if I remembered correctly, these tests always failed on Hera for whatever reason that I didn't explore.
On Orion, I encountered segmentation fault error while running `test_soca_gridgen` so I was not able to run the rest of the ctests. I suspect it was a machine related issue instead of MOM6 updates.
```
4: ==== backtrace (tid: 366492) ====
4:  0 0x00000000002c6bf4 mom_mp_initialize_mom_()  /work/noaa/ng-godas/xliu/prs/pr_review/soca/bundle/mom6/src/core/MOM.F90:1776
4:  1 0x000000000023662f soca_mom6_mp_soca_mom6_init_()  ???:0
4:  2 0x000000000019b250 soca_geom_mod_mp_soca_geom_gridgen_()  ???:0
4:  3 0x00000000001ac39c soca_geo_gridgen_f90()  ???:0
4:  4 0x0000000000406c35 soca::GridGen::execute()  ???:0
4:  5 0x00000000000db68b oops::Run::execute()  ???:0
4:  6 0x0000000000406a66 main()  ???:0
4:  7 0x0000000000022495 __libc_start_main()  ???:0
4:  8 0x0000000000406929 _start()  ???:0
4: =================================
4: srun: error: Orion-01-08: tasks 0-1: Segmentation fault
4: srun: launch/slurm: _step_signal: Terminating StepId=4343877.2
4: Failed to run executable. Error code: 139 
4: 
2/2 Test #4: test_soca_gridgen ................***Failed   24.51 sec
```

**Comment by kbhargava** [comment]
> 

I have the same issue on Orion as @liuxiao37k . @guillaumevernieres My log files are at `/home/kritib/work/test_repos/soca/build.intel/soca/Testing/Temporary/LastTest.log` if you want to have a look.

**Comment by liuxiao37k** [comment]
FYI - I also tested with soca-science; build was successful, but cycling ctests failed due to same segmentation error during `prep.soca` step, so at least the error behavior was consistent.

**Comment by guillaumevernieres** [comment]
Thanks for testing @liuxiao37k, @HamidehGMAO and @kbhargava , I'll have a look. What intel version are we using on Hera @liuxiao37k ?

**Comment by liuxiao37k** [comment]
> Thanks for testing @liuxiao37k and @kbhargava , I'll have a look. What intel version are we using on Hera @liuxiao37k ?

@guillaumevernieres: module load jedi/intel-impi/2020.2

**Comment by guillaumevernieres** [comment]
I don't know ... It seems to work for me now (it was failing earlier today):

hummmmmm

4, 45 and 52 fail in the compare step but the other tests are OK.

**Review by liuxiao37k — APPROVED** [review]
whew! works for me now. All soca ctests passed except the three that you @guillaumevernieres identified. I also ran soca-science ctests including all BGC ones. No issues. So I am approving the PRs before something goes wrong again...

**Review by clouden90 — APPROVED** [review]
Tested it with this [PR](https://github.com/JCSDA-internal/soca/pull/701). Looks ok.

**Review by kbhargava — APPROVED** [review]
looks good except the 3 ctests that fail because of tolerance threshold set. Tested on orion.

**Review by kbhargava — APPROVED** [review]

**Review by travissluka — APPROVED** [review]

**Pull request merged**
